apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
        name: cf-dns
spec:
        acme:
                email: contact@noc.matthew-cloud.com
                server: https://acme-v02.api.letsencrypt.org/directory
                privateKeySecretRef: is-a-k
                solvers:
                        - dns01:
                                cloudflare:
                                        email: matthewzhaocc@gmail.com
                                        apiKeySecretRef:
                                                name: cf-key
                                                key: cfkey
